<!DOCTYPE html>
<!--[if IE]><![endif]-->
<html>
  
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Electronic invoices (CFDI) | WIKA Documentation </title>
    <meta name="viewport" content="width=device-width">
    <meta name="title" content="Electronic invoices (CFDI) | WIKA Documentation ">
    <meta name="generator" content="docfx 2.56.6.0">
    
    <link rel="shortcut icon" href="../../../microsoft-dynamics-crm-365-icon.ico">
    <link rel="stylesheet" href="../../../styles/docfx.vendor.css">
    <link rel="stylesheet" href="../../../styles/docfx.css">
    <link rel="stylesheet" href="../../../styles/main.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet"> 
    <meta property="docfx:navrel" content="../../../toc.html">
    <meta property="docfx:tocrel" content="../TOC.html">
    
    
    
  </head>  <body data-spy="scroll" data-target="#affix" data-offset="120">
    <div id="wrapper">
      <header>
        
        <nav id="autocollapse" class="navbar navbar-inverse ng-scope" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              
              <a class="navbar-brand" href="../../../index.html">
                <img id="logo" class="svg" src="../../../logo.svg" alt="">
              </a>
            </div>
            <div class="collapse navbar-collapse" id="navbar">
              <form class="navbar-form navbar-right" role="search" id="search">
                <div class="form-group">
                  <input type="text" class="form-control" id="search-query" placeholder="Search" autocomplete="off">
                </div>
              </form>
            </div>
          </div>
        </nav>
        
        <div class="subnav navbar navbar-default">
          <div class="container hide-when-search" id="breadcrumb">
            <ul class="breadcrumb">
              <li></li>
            </ul>
          </div>
        </div>
      </header>
      <div role="main" class="container body-content hide-when-search">
        
        <div class="sidenav hide-when-search">
          <a class="btn toc-toggle collapse" data-toggle="collapse" href="#sidetoggle" aria-expanded="false" aria-controls="sidetoggle">Show / Hide Table of Contents</a>
          <div class="sidetoggle collapse" id="sidetoggle">
            <div id="sidetoc"></div>
          </div>
        </div>
        <div class="article row grid-right">
          <div class="col-md-10">
            <article class="content wrap" id="_content" data-uid="">
<h1 id="electronic-invoices-cfdi">Electronic invoices (CFDI)</h1>


<p>Electronic billing in Mexico requires the Comprobantes fiscales digitales por internet (CFDI) format.</p>
<p>This article provides information about the electronic invoices that your organization can submit to the Mexican tax authority (SAT). It describes the currently approved method for submitting electronic invoices (CFDI), the requirements for using them, and the information that they include.</p>
<p>An electronic invoice is a legally accepted digital tax receipt that your organization submits to the Mexican tax authority (Servicio de Administración Tributaria [SAT]). Dynamics 365 Finance helps guarantee that the electronic invoices that your organization generates are secure, confidential, authentic, and legally acceptable. You can also make sure that international standards are applied to your electronic invoices. You can generate an electronic invoice for the following documents when a transaction is posted:</p>
<ul>
<li>Sales order</li>
<li>Free text invoice</li>
<li>Credit note</li>
<li>Return order</li>
<li>Project invoice</li>
<li>Project sales order</li>
</ul>
<h2 id="methods-for-generating-electronic-invoices">Methods for generating electronic invoices</h2>
<p>There are two methods for generating electronic invoices:</p>
<ul>
<li><strong>Comprobantes fiscales digitales (CFD)</strong> – Electronic invoices are generated by using Finance. The invoices are then verified and certified by using a government website. Finally, your organization submits the invoices to SAT. Although this method is now obsolete because of changes in the legislation, you can inquire about CFD transactions that were previously generated in Finance.</li>
<li><strong>Comprobantes fiscales digitales por internet (CFDI)</strong> – This is the current method for generating electronic invoices in the format that SAT requires. In this method, the invoices are verified and certified by a digital signature service provider (PAC). Before you can use the CFDI method to generate electronic invoices, your organization must set up a web service connection to an authorized PAC. For the CFDI method, you send an XML message from Finance to the PAC. The PAC validates each invoice, assigns a folio number, and then incorporates the digital stamp that the service tax authorities provide. After the PAC completes the approval process, your organization receives the approved XML message, and can then submit the invoice to the customer in XML or PDF format.</li>
</ul>
<div class="NOTE">
<h5>Note</h5>
<p>Integration with the PAC web service is not part of the Mexican localization. For information about how to customize a web service connection with a PAC, see “Customizing the integration with PAC web services” later in this article.</p>
</div>
<p>The following illustration shows the process for generating an electronic invoice by using the CFDI method.</p>
<p><img src="./media/about-electronic-invoices-cfdi.jpg" alt="The electronic invoice process for Mexico" title="Electronic invoicing generation process for CFDI method">    </p>
<h3 id="requirements-for-using-electronic-invoices">Requirements for using electronic invoices</h3>
<p>To use electronic invoices, your organization must complete the following tasks:</p>
<ul>
<li>Obtain authorization from SAT to use the CFDI method, and acquire the related SAT certificate to issue electronic invoices.</li>
<li>Obtain a Registro Federal de Contribuyentes (RFC) number, a Clave Única de Registro de Población (CURP) number, and a state inscription number from SAT.</li>
<li>Contract a PAC web service. You can find the authorized PAC services on the SAT website. Some PACs require that you install an additional certificate to enable the connection between your instance of Finance and the PAC web service.</li>
<li>Make sure that PDF and XML files meet SAT requirements. These files are sent to customers as email attachments. The XML file that is generated must be based on the XML schema definition (XSD) that SAT provides. You must archive the XML file of each electronic invoice.</li>
<li>An RFC or CURP tax registration ID is required for your organization and your customers. Be sure to complete this information in the related configuration.</li>
<li>Install the SAT certificate and PAC service certificate on the server, and make sure that the NETWORK SERVICE user has the appropriate permissions for private keys.</li>
<li>Identify the PAC web service that is used. (Click <strong>Accounts receivable</strong> &gt; <strong>Invoices</strong> &gt; <strong>E-invoice</strong> &gt; <strong>PAC accounts</strong>.) You can use test and production environments if your PAC services allow for these types of environments.</li>
<li>Enable the configuration to send email, and define the email template that is used to transmit XML and PDF files. (Click <strong>Organization administration</strong> &gt; <strong>Setup</strong> &gt; <strong>E-mail parameters</strong>.)</li>
<li>Enable the configuration to issue CFDI electronic invoices. (Click <strong>Accounts receivable</strong> &gt; <strong>Invoices</strong> &gt; <strong>E-invoice</strong> &gt; <strong>Electronic invoice parameters</strong>.)</li>
<li>Prepare the integration with your PAC web service.</li>
</ul>
<h3 id="information-that-is-included-in-electronic-invoices">Information that is included in electronic invoices</h3>
<p>An electronic invoice includes the following details:</p>
<ul>
<li>The name, address, and tax registration numbers of your organization and the customer.</li>
<li>The invoice number, the date, and the name of the city where the invoice was generated.</li>
<li>The serial number of the digital certificate, the authorization number, and the year when the certificate was authorized.</li>
<li>The description and quantity of each item that is included in the invoice.</li>
<li>The unit price of each item.</li>
<li>The amount that was withheld for income tax (Impuesto sobre la renta [ISR]) and value-added tax (VAT). To obtain this information, you must set up the tax type (VAT or ISR) on the <strong>Sales tax code configuration</strong> page (click <strong>Tax</strong> &gt; <strong>Indirect taxes, Sales tax</strong> &gt; <strong>Sales tax code</strong> &gt; <strong>General</strong> &gt; <strong>Tax type</strong>).</li>
<li>The total amount of the invoice transaction.</li>
<li>The name, number, and date of the customs document that is generated for imported items. This information is available in each invoice transaction form that is mentioned earlier.</li>
<li>The registration number of the property if the invoice transaction includes leasing services. This information is available in each invoice transaction form that is mentioned earlier.</li>
<li>The digital stamp of the organization.</li>
<li>For a printed CFDI version, the bidimensional bar code.</li>
</ul>
<h2 id="customizingthe-integration-pac-web-services">Customizing the integration PAC web services</h2>
<p>As is explained in detail in the Mexican localization scope document, integration with PAC web services requires customization. This customization varies, depending on the PAC web services that are contracted.</p>
<h2 id="additional-resources">Additional resources</h2>
<ul>
<li><a href="tasks/mx-00010-e-invoicing-cfdi.html">E-invoicing CFDI</a></li>
<li><a href="tasks/mx-00010-inquire-print-electronic-invoice.html">Inquire and print an electronic invoice</a></li>
<li><a href="tasks/mx-00010-cancel-electronic-invoice.html">Cancel an electronic invoice</a></li>
<li><a href="latam-mex-cfdi-3-3.html">CFDI layout Version 3.3</a></li>
</ul>
</article>
          </div>
          
          <div class="hidden-sm col-md-2" role="complementary">
            <div class="sideaffix">
              <div class="contribution">
                <ul class="nav">
                </ul>
              </div>
              <nav class="bs-docs-sidebar hidden-print hidden-xs hidden-sm affix" id="affix">
                <h5>In This Article</h5>
                <div></div>
              </nav>
            </div>
          </div>
        </div>
      </div>
      
      <footer>
        <div class="grad-bottom"></div>
        <div class="footer">
          <div class="container">
            <span class="pull-right">
              <a href="#top">Back to top</a>
            </span>
            
            <span>Generated by <strong>DocFX</strong></span>
          </div>
        </div>
      </footer>
    </div>
    
    <script type="text/javascript" src="../../../styles/docfx.vendor.js"></script>
    <script type="text/javascript" src="../../../styles/docfx.js"></script>
    <script type="text/javascript" src="../../../styles/main.js"></script>
  </body>
</html>
